name: 'Check code quality'

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: checkCodeQuality-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkCodeQuality:
    name: 'Check code quality'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: 'Setup Project'
        uses: ./.github/actions/setup-project

      - name: 'Check code quality'
        uses: ./.github/actions/check-code-quality
